import { ReactNode } from "react";
import "./globals.css";

export const metadata = {
  title: "Codebin Editor",
  description: "Generated by create next app",
};

type NewPageLayoutProps = {
  children: ReactNode;
};

export default function NewPageLayout({ children }: NewPageLayoutProps) {
  return (
    <>
      <main className="min-h-[100vh]">{children}</main>;
    </>
  );
}
